// this file is autogenerated from the wheels in the pypi directory
export const allJSONUrl = "pypi/all.json";
export const ipykernelWheelUrl = "pypi/ipykernel-6.9.2-py3-none-any.whl";
export const pipliteWheelUrl = "pypi/piplite-0.6.0a5-py3-none-any.whl";
export const pyodide_kernelWheelUrl = "pypi/pyodide_kernel-0.6.0a5-py3-none-any.whl";
export const widgetsnbextensionWheelUrl = "pypi/widgetsnbextension-3.6.999-py3-none-any.whl";
export const widgetsnbextensionWheelUrl1 = "pypi/widgetsnbextension-4.0.999-py3-none-any.whl";
